language: cpp

os: osx

osx_image: xcode12u

addons:
  sonarcloud:
    organization: "longcat-mobile-github"
    token:
      secure: "PWwo9hiCB6WYKRbY3ZIZdDHbbW0yL4t/J5n+BlUk52Z4Ydpq6yJ8ecbki81IQPvotomt3wI0RpnaD92CR4XmkUf6EgTklxmFWCryzLanx3QoSQYPfh9wKSvQ/+kHdWpQfpWXPpOSsiUDQNYZU40fUbFMcS7iMxM0dwLqduR9zCVKCUFShujWiKEkagyVq2hzWUEotYWRQJwzIY82dhsaHxkDAZb6QyZZS77Z7N6+vm9eAm/QGqyRIYY0FuI48tGwTP1PSNn9EMa0oDq9+QibIkYAXNBjNu6y4O/MGkTO3oReBmKqq6nuXjqMgzwy/48M05EZKWHXreIQlvLzgkJ7QA3fZ5fP81+0ahWZR2zOs8ZuFhInpSU5GJQ7Fqeu1ilJBmaWAoaaJKSzUmkn7+ipfalBey5p5KEM0zsZJ2RWrMOrxi8yxbYlyYLep2H71SMHmsIz0NYHOkKr01Kzpau38/QiBxUFICZFzXpaAkW9hgbEim0530wEQ1IYywPULbmJJEeTjEV3tLOwzzEcIqSqJGo9SBlM/AXrnsja2OHL6AOoIXANDT/SGjONEl4w/J/UQYPcJ2pEoNwdcIWq6quTczkMWVcPFc7iiXggxRyZerzXfo4UO7JgiK3mqc6SaX+u7OEu14k3POmn9k/lyPjEOI/mxstaNFlia8KWYXdKPTU="

install:
  - |
    echo && \
    echo "---- INSTALLATION OF HOMEBREW PACKAGES ----" && \
    echo && \
    brew install p7zip && \
    echo && \
    echo "------- INSTALLATION OF QT PACKAGES -------" && \
    echo && \
    bash tools/install-qt.sh --version 5.12.9 --target ios --toolchain ios --directory "$HOME/Qt" qtbase qtdeclarative qtquickcontrols2 qtmultimedia qtpurchasing && \
    echo && \
    echo "----------- END OF INSTALLATION -----------" && \
    echo

script:
  - |
    echo && \
    echo "---------- ENVIRONMENT VARIABLES ----------" && \
    echo && \
    export PATH="$HOME/Qt/5.12.9/ios/bin:$PATH" && \
    export QMAKE_CFLAGS_ENV="-Werror" && \
    export QMAKE_CXXFLAGS_ENV="-Werror" && \
    export QMAKE_OBJECTIVE_CFLAGS_ENV="-Werror -Wno-error-objc-property-no-attribute" && \
    echo && \
    echo "--------- UNSHALLOW GIT FOR SONAR ---------" && \
    echo && \
    git fetch --unshallow && \
    echo && \
    echo "---------- CREATE BUILD DIRECTORY ---------" && \
    echo && \
    mkdir .build && \
    cd .build && \
    echo && \
    echo "------------------ QMAKE ------------------" && \
    echo && \
    qmake ../longcat.pro && \
    echo && \
    echo "------------------ MAKE -------------------" && \
    echo && \
    make XCODEBUILD_FLAGS="CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO" debug-device && \
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then \
        echo && \
        echo "------------- MAKE DISTCLEAN --------------" && \
        echo && \
        make distclean && \
        echo && \
        echo "------------------ QMAKE ------------------" && \
        echo && \
        qmake ../longcat.pro && \
        echo && \
        echo "-------------- SONAR WRAPPER --------------" && \
        echo && \
        build-wrapper-macosx-x86 --out-dir bw-output make XCODEBUILD_FLAGS="CODE_SIGN_IDENTITY=\"\" CODE_SIGNING_REQUIRED=NO" debug-device && \
        echo && \
        echo "-------------- SONAR SCANNER --------------" && \
        echo && \
        cd .. && \
        sonar-scanner -Dsonar.projectKey=longcat-mobile_longcat-ios \
                      -Dsonar.projectName="Longcat iOS" \
                      -Dsonar.sources=. \
                      -Dsonar.sourceEncoding=UTF-8 \
                      -Dsonar.exclusions="qml_*.cpp,qrc_*.cpp,ios/frameworks/**/*,qml/**/*,translations/*" \
                      -Dsonar.cfamily.build-wrapper-output=.build/bw-output \
                      -Dsonar.cfamily.cache.enabled=false \
                      -Dsonar.cfamily.threads=1 \
                      -Dsonar.cpp.file.suffixes=.cpp,.mm; \
    fi
